In [5]:
'''
Chapter 4 of the Python Data Analytics book
'''
import pandas as pd  #inporting pandas
import numpy as np

s = pd.Series([12,-4,7,9])   #creating arrays...as far series it is like an array except it comes with index built in
print(s)

0    12
1    -4
2     7
3     9
dtype: int64


In [6]:
print(s*2)   #multiplying the entire series is pretty easy here

0    24
1    -8
2    14
3    18
dtype: int64


In [7]:
s2 = pd.Series([12,-4,7,9], index=['a','b','c','d'])
print(s2)

a    12
b    -4
c     7
d     9
dtype: int64


In [8]:
s2.values     #values is an attribute, not a function 

array([12, -4,  7,  9], dtype=int64)

In [9]:
s2.index  #you can see with index attribute as to how many

Index(['a', 'b', 'c', 'd'], dtype='object')

# SELECTING INTERNAL ELEMENT   => numpy and pandas 

In [11]:
#SELECTING INTERNAL ELEMENT   => numpy and pandas 

print(s[0])
print(s[1])
print(s[2])


12
-4
7


In [10]:
s2[0:2]   #remember, index[2]is not included but upto or less than.

a    12
b    -4
dtype: int64

In [11]:
#Assigning values to the element using pandas and numpy (p.95)
print(s2)
s2['b']=100   #assigned the element from -4 => 100
print(s2)


a    12
b    -4
c     7
d     9
dtype: int64
a     12
b    100
c      7
d      9
dtype: int64


In [13]:
#Deifining a Series from NumPy Arrays and other series
arr = np.array([1,2,3,4])
print(arr)
s3 = pd.Series(arr)
print(s3)

[1 2 3 4]
0    1
1    2
2    3
3    4
dtype: int32


In [14]:
s3[0] = 100
print(s3)    #by changing the s3, the pointers that was passed => arr and the value is now changed also from it

0    100
1      2
2      3
3      4
dtype: int32


In [15]:
print(arr)

[100   2   3   4]


In [16]:
#Filtering Values:  page 97
print(s3)

0    100
1      2
2      3
3      4
dtype: int32


In [17]:
s3[s3>99]   #gets you the only value that is above 99 in this case, but will not change the underlying value of the series

0    100
dtype: int32

In [18]:
print(s3)  #printing the series as it shows it is no 'in place'

0    100
1      2
2      3
3      4
dtype: int32


In [19]:
#Operations and Mathematical Functions: 
#same as usual (+, -, *, /)
s3/2


0    50.0
1     1.0
2     1.5
3     2.0
dtype: float64

In [20]:
s3   #again this keeps the s3 value intact

0    100
1      2
2      3
3      4
dtype: int32

In [21]:
np.log(s3)

0    4.605170
1    0.693147
2    1.098612
3    1.386294
dtype: float64

In [22]:
print(s3)

0    100
1      2
2      3
3      4
dtype: int32


# Evaluating Values

In [24]:
#Evaluating Values Page 98
serd = pd.Series([1,0,2,1,2,3], index=['white', 'white', 'blue', 'green', 'green', 'yellow'])

In [25]:
print(serd)

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64


In [26]:
serd.unique()   #this is like set() for the value where only unique values are displayed 

array([1, 0, 2, 3], dtype=int64)

In [29]:
serd.value_counts()    #this gives you the # counts of the values

2    2
1    2
3    1
0    1
dtype: int64

In [30]:
print(serd)
print(serd.isin([0,3]))   # isin() function like => 3 in range(10)

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64
white     False
white      True
blue      False
green     False
green     False
yellow     True
dtype: bool


# handling NaN values Page 99

In [34]:
sp1 = pd.Series([5, -3, np.NaN,14])  #Creating series
print(sp1)
print(sp1.isnull())   #checking if there is null
print(sp1.notnull())

0     5.0
1    -3.0
2     NaN
3    14.0
dtype: float64
0    False
1    False
2     True
3    False
dtype: bool
0     True
1     True
2    False
3     True
dtype: bool


In [35]:
sp1[sp1.isnull()]   #this is like {k,v where condition(True)}

2   NaN
dtype: float64