# Array Inpu/Output Python_Numpy 3_20_2020

In [5]:
import numpy as np

arr = np.arange(5)
print(arr)
np.save('myarray',arr)   #this np.save('<name>',source_array) will save it in the same directory

[0 1 2 3 4]


In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr1 = np.load('myarray.npy')      #This function loads the array that you saved with .npy extension

In [8]:
arr1

array([0, 1, 2, 3, 4])

In [9]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.savez('ziparray.npz',x = arr1, y=arr2)   #npz and savez() saves multiple arrays in a zip 

In [11]:
archive_array = np.load('ziparray.npz')   #This loads it back up

In [12]:
archive_array

In [14]:
archive_array['x']      #you have to specify the content via [0], [x]  etc.,

array([0, 1, 2, 3, 4])

In [15]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.savetxt('mytextarray.txt',arr3, delimiter=',')

In [10]:
arr33 = np.loadtxt('mytextarray.txt', delimiter = ',')
arr33

array([[1., 2., 3.],
       [4., 5., 6.]])