# Python Pandas concatnate() Lesson 31 3_28_2020

In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.concatenate([arr1,arr1], axis =1) #along x axis

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [9]:
np.concatenate([arr1, arr1])  # along y axis (as added records)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
ser1 = Series([0,1,2], index=['T','U','V'])

In [11]:
ser1

T    0
U    1
V    2
dtype: int64

In [12]:
ser2 = Series([3,4], index =['X','Y'])

In [14]:
print(ser1)
print(ser2)

T    0
U    1
V    2
dtype: int64
X    3
Y    4
dtype: int64


In [15]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [16]:
pd.concat([ser1,ser2],axis =1)

c:\users\dicei\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [17]:
pd.concat([ser1, ser2],axis =1, sort =True)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [20]:
pd.concat([ser1,ser2],axis = 0, sort =True, keys = ['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [28]:
dframe = DataFrame(np.random.randn(4,3),columns = ['X','Y','Z'])
print(dframe)

          X         Y         Z
0  0.321127 -1.432286  0.086677
1 -0.633041 -0.711741  1.428455
2  0.040426 -1.252776 -0.493186
3  0.484290 -0.322103  1.412925


In [27]:
dframe2 = DataFrame(np.random.randn(3,3), columns = ['Y','Q','X'])
print(dframe2)

          Y         Q         X
0 -1.020094  0.989680 -0.128140
1  0.662463 -0.093531 -0.352686
2  0.035994 -0.522230  0.364445


In [26]:
pd.concat([dframe,dframe2])

c:\users\dicei\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  0.588865  1.148866  1.423412
1       NaN  0.223888 -0.603200 -1.147552
2       NaN  0.193497 -0.276291  0.509902
3       NaN -0.379968  0.874770  0.863724
0  1.083040  1.822244 -1.050112       NaN
1  1.181617 -0.835198  0.769395       NaN
2 -0.748314  0.798615 -0.343002       NaN

In [29]:
pd.concat([dframe,dframe2],ignore_index = True)

c:\users\dicei\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  0.321127 -1.432286  0.086677
1       NaN -0.633041 -0.711741  1.428455
2       NaN  0.040426 -1.252776 -0.493186
3       NaN  0.484290 -0.322103  1.412925
4  0.989680 -0.128140 -1.020094       NaN
5 -0.093531 -0.352686  0.662463       NaN
6 -0.522230  0.364445  0.035994       NaN